name: .NET Core CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.306

    - name: Install dependencies
      run: dotnet restore SimpleCalculator_Test.sln

    - name: Build
      run: dotnet build SimpleCalculator_Test.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test SimpleCalculator_Test.sln --no-restore --verbosity normal
